---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app holmesgpt-slack-secret
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: 1password-operator
      namespace: 1password
  interval: 1h
  path: ./flux/apps/base/holmesgpt/slack-secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: holmesgpt
  timeout: 5m
  prune: true
  wait: true
