---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
components:
  # The failing-job container runs restricted (non-root, no caps, RO rootfs)
  - ../../../infra/namespace

resources:
  - ./failing-job/ks.yaml
