---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
components:
  # kagent worker pods may need elevated permissions for tool execution
  - ../../../infra/namespace-privileged

resources:
  - ./crds/ks.yaml
  - ./model-secret/ks.yaml
  - ./operator/ks.yaml
  - ./qdrant-mcp/ks.yaml
  - ./qdrant-sandbox/ks.yaml
  - ./ui/ks.yaml
